### ISSUE TITLE
Not Registering on Website

### ISSUE THREAD

**Issue by MadHatRecon** [unstabl3/breakfold#4]
Hi there, so I'm using kali 2020 followed all the instruction by the letter. Firstly I was testing on my own website. So when I run the program without sudo, breakfold reutrns an error after one view. The website registers the view.
When I run breakfold with sudo it runs through but the website doesn't register any views.

Do you have any idea what this could be?
![breakfold1](https://user-images.githubusercontent.com/69061642/89088651-8e41f180-d367-11ea-8d11-be93dec0c2bd.png)
![breakfold2](https://user-images.githubusercontent.com/69061642/89088657-9306a580-d367-11ea-89d2-064296befd9f.png)

**Comment by unstabl3** [comment]
Hi @MadHatRecon 

I'm not sure why it doesn't register at a website. Not all websites are supported. I have done very minimal testing with this script. long time back when I checked with WordPress it fails to register a view. I don't know if this still works with WordPress.

Also, as per the first image running without sudo will give you an error if there is a lack of permissions for the user.
Internally stem library will talk with /etc which needs permission.
If you don't want to use sudo try to give permission to lower privileged users.
If this still doesn't work try editing line 53 of breakfold.py and put your tor password inside quotes.

Thanks,
@unstabl3
